deployment:
  tasks:
    - export DEPLOYPATH=/home/eliteflight/public_html/
    - cd C:\Sheikh Project\Elite-flight\dist\assets || { echo "Directory not found"; exit 1; }
    - npm install || { echo "npm install failed"; exit 1; }
    - npm run build || { echo "Build failed"; exit 1; }
    - cp -r build/* $DEPLOYPATH || { echo "Copy failed"; exit 1; }
    - echo "Deployment complete" # Optional: to add a log entry
