---
deployment:
  tasks:
    - export DEPLOYPATH=/home/eliteflight/public_html/
    - cd /path/to/your/react/project
    - npm install   # Install dependencies
    - npm run build # Build the React project
    - cp -r build/* $DEPLOYPATH
