---
deployment:
  tasks:
    - export DEPLOYPATH=/home/eliteflight/public_html/
    - cd "C:\Sheikh Project\Elite-flight"
    - npm install   # Install dependencies
    - npm run build # Build the React project
    - cp -r build/* $DEPLOYPATH
